version: 0.0.1.{build}

shallow_clone: true

cache:
  - "%APPDATA%\\stack"
  - .stack-work
  - "inline-js\\.stack-work"
  - "inline-js-examples\\.stack-work"
  - "inline-js\\.buildinfo"
  - "inline-js-examples\\.buildinfo"

build_script:
  - choco install haskell-stack nodejs
  - stack --no-terminal setup > NUL
  - stack --no-terminal build --haddock --test --no-run-tests

test_script:
  - stack --no-terminal test inline-js-examples:inline-js-examples
