name: inline-js
version: 0.0.1
category: Language
synopsis: Execute Node.js scripts in Haskell.
stability: alpha
maintainer: Shao Cheng <cheng.shao@tweag.io>
copyright: (c) 2018 EURL Tweag
license: BSD3
github: tweag/inline-js

extra-source-files:
  - LICENSE
  - README.md
  - CHANGELOG.md

data-files:
  - jsbits/package.json
  - jsbits/server.js

ghc-options: -Wall

dependencies:
  - aeson
  - base
  - binary
  - bytestring
  - Cabal
  - directory
  - extra
  - filepath
  - ghc-prim
  - hashable
  - megaparsec
  - mtl
  - primitive
  - process
  - template-haskell
  - text
  - unliftio
  - unordered-containers
  - websockets

library:
  source-dirs: src
  other-modules:
    - Language.JavaScript.Inline.Internals.MsgId
    - Language.JavaScript.Inline.Internals.Parser
    - Language.JavaScript.Inline.Internals.SessionTypes
    - Paths_inline_js
  other-extensions:
    - ApplicativeDo
    - BangPatterns
    - DeriveAnyClass
    - DeriveFunctor
    - DuplicateRecordFields
    - FlexibleInstances
    - GeneralizedNewtypeDeriving
    - LambdaCase
    - MagicHash
    - MultiParamTypeClasses
    - OverloadedLists
    - OverloadedStrings
    - RankNTypes
    - RecordWildCards
    - ScopedTypeVariables
    - StandaloneDeriving
    - StrictData
    - TemplateHaskell
    - UnboxedTuples
    - UndecidableInstances
