version: 2

jobs:
  inline-js-test-cabal:
    docker:
      - image: terrorjack/pixie:latest
    resource_class: xlarge
    steps:
      - run:
          name: Install dependencies
          command: |
            nix-channel --add https://releases.nixos.org/nixpkgs/nixpkgs-19.09pre174594.0c0954781e2 nixpkgs
            nix-channel --update
            nix-env -u
            nix-env -iA \
              nixpkgs.cabal-install \
              nixpkgs.gitMinimal \
              nixpkgs.gnutar \
              nixpkgs.gzip \
              nixpkgs.haskell.compiler.ghc844 \
              nixpkgs.nodejs-11_x \
              nixpkgs.openssh
            cabal new-update
      - checkout
      - run:
          name: Test inline-js
          command: |
            cabal new-run inline-js:inline-js-test-suite -- -j8

  inline-js-test-stack:
    docker:
      - image: terrorjack/pixie:latest
    resource_class: xlarge
    steps:
      - run:
          name: Install dependencies
          command: |
            nix-channel --add https://releases.nixos.org/nixpkgs/nixpkgs-19.09pre174594.0c0954781e2 nixpkgs
            nix-channel --update
            nix-env -u
            nix-env -iA \
              nixpkgs.gitMinimal \
              nixpkgs.gnutar \
              nixpkgs.gzip \
              nixpkgs.openssh \
              nixpkgs.stack
      - checkout
      - run:
          name: Test inline-js
          command: |
            stack --nix --no-terminal build --haddock --test --no-run-tests
            stack --nix --no-terminal test inline-js --test-arguments="-j8"
