version: 2

jobs:
  build:
    docker:
      - image: terrorjack/pixie:latest
    resource_class: xlarge
    steps:
      - run:
          name: Install dependencies
          command: |
            nix-channel --add https://releases.nixos.org/nixpkgs/nixpkgs-19.09pre173445.796a8764ab8 nixpkgs
            nix-channel --update
            nix-env -u
            nix-env -iA \
              nixpkgs.gitMinimal \
              nixpkgs.gnutar \
              nixpkgs.gzip \
              nixpkgs.openssh \
              nixpkgs.stack
      - checkout
      - run:
          name: Test inline-js and inline-js-core
          command: |
            stack --no-terminal build inline-js-core inline-js --test --no-run-tests
            stack --no-terminal test inline-js
