version: 2
jobs:
  build:
    docker:
      - image: nixorg/nix:circleci
    environment:
      SSL_CERT_FILE: /nix/var/nix/profiles/default/etc/ssl/certs/ca-bundle.crt
    steps:
      - run: |
          nix-channel --add https://nixos.org/channels/nixpkgs-unstable
          nix-channel --update
          nix-env -iA \
            nixpkgs.cacert \
            nixpkgs.stack \
            nixpkgs.strace
          mkdir ~/.stack
          printf "nix:\n  enable: true\n" > ~/.stack/config.yaml
      - checkout
      - restore_cache:
          key: stack-work-gen5-
      - run: |
          ls /etc/ssl/certs/
          strace -e trace=open,execve -f stack --no-terminal build --haddock --test --no-run-tests
      - save_cache:
          key: stack-work-gen5-
          paths:
            - /root/.stack
            - .stack-work
            - examples/.stack-work
            - .buildinfo
            - examples/.buildinfo
      - run: |
          stack --no-terminal test inline-js-examples:inline-js-examples
          if [ $CIRCLE_PROJECT_USERNAME == "tweag" ] && [ $CIRCLE_BRANCH == "master" ]
          then
            cd `stack path --local-doc-root`
            touch .nojekyll
            git init
            git config user.email "cheng.shao@tweag.io"
            git config user.name "Shao Cheng"
            git checkout -b gh-pages
            git add --all
            git commit -q --message="Haddock documentation of tweag/inline-js@$CIRCLE_SHA1"
            git push https://TerrorJack:$GH_TOKEN@github.com/tweag/inline-js.git gh-pages --force
          fi
