version: 2

jobs:
  inline-js-test-nodejs-12:
    docker:
      - image: terrorjack/stackage:lts-14.11
    steps:
      - run:
          name: Install dependencies
          command: |
            curl -sSL https://deb.nodesource.com/gpgkey/nodesource.gpg.key | apt-key add -
            echo "deb https://deb.nodesource.com/node_12.x sid main" > /etc/apt/sources.list.d/nodesource.list
            apt update
            apt full-upgrade -y
            apt install -y nodejs
            node --version
            npm --version
      - checkout
      - run:
          name: Test inline-js
          command: |
            stack --no-terminal -j2 build --haddock --test --no-run-tests
            stack --no-terminal test inline-js --test-arguments="-j2"

  inline-js-test-nodejs-13:
    docker:
      - image: terrorjack/stackage:lts-14.11
    steps:
      - run:
          name: Install dependencies
          command: |
            curl -sSL https://deb.nodesource.com/gpgkey/nodesource.gpg.key | apt-key add -
            echo "deb https://deb.nodesource.com/node_13.x sid main" > /etc/apt/sources.list.d/nodesource.list
            apt update
            apt full-upgrade -y
            apt install -y nodejs
            node --version
            npm --version
      - checkout
      - run:
          name: Test inline-js
          command: |
            stack --no-terminal -j2 build --haddock --test --no-run-tests
            stack --no-terminal test inline-js --test-arguments="-j2"

  inline-js-test-nodejs-v8:
    docker:
      - image: terrorjack/stackage:lts-14.11
    steps:
      - run:
          name: Install dependencies
          command: |
            apt update
            apt full-upgrade -y
            cd /usr
            curl -L https://raw.githubusercontent.com/tweag/asterius/master/utils/v8-node.py | python3
            export npm_config_prefix=/usr
            curl -L https://www.npmjs.com/install.sh | sh
            node --version
            npm --version
      - checkout
      - run:
          name: Test inline-js
          command: |
            stack --no-terminal -j2 build --haddock --test --no-run-tests
            stack --no-terminal test inline-js --test-arguments="-j2"

  inline-js-test-macos:
    macos:
      xcode: "11.1.0"
    steps:
      - run:
          name: Install dependencies
          command: |
            brew update
            brew upgrade
            brew install \
              haskell-stack \
              node
      - checkout
      - run:
          name: Test inline-js
          command: |
            stack --no-terminal -j4 build --test --no-run-tests
            stack --no-terminal test inline-js --test-arguments="-j4"

workflows:
  version: 2
  build:
    jobs:
      - inline-js-test-nodejs-12
      - inline-js-test-nodejs-13
      - inline-js-test-nodejs-v8
      - inline-js-test-macos
