version: 2

jobs:
  inline-js-test-nix:
    docker:
      - image: terrorjack/pixie:latest
    resource_class: xlarge
    steps:
      - run:
          name: Install dependencies
          command: |
            nix-channel --add https://releases.nixos.org/nixpkgs/nixpkgs-19.09pre180124.920d066ded1 nixpkgs
            nix-channel --update
            nix-env -u
            nix-env -iA \
              nixpkgs.gitMinimal \
              nixpkgs.openssh
      - checkout
      - run:
          name: Test inline-js
          command: |
            nix-shell \
              --command "cabal new-run inline-js:inline-js-test-suite -- -j8" \
              --pure \
              -p cabal-install \
              -p nodejs-12_x \
              -p "haskellPackages.ghcWithPackages (pkgs: [pkgs.aeson pkgs.base64-bytestring pkgs.language-javascript pkgs.tasty-hspec pkgs.tasty-quickcheck pkgs.tasty-smallcheck])"

  inline-js-test-stack:
    docker:
      - image: terrorjack/pixie:latest
    resource_class: xlarge
    steps:
      - run:
          name: Install dependencies
          command: |
            nix-channel --add https://releases.nixos.org/nixpkgs/nixpkgs-19.09pre180124.920d066ded1 nixpkgs
            nix-channel --update
            nix-env -u
            nix-env -iA \
              nixpkgs.gitMinimal \
              nixpkgs.openssh \
              nixpkgs.stack
      - checkout
      - run:
          name: Test inline-js
          command: |
            stack --nix --no-nix-pure --no-terminal build --haddock --test --no-run-tests
            stack --nix --no-nix-pure --no-terminal test inline-js --test-arguments="-j8"

workflows:
  version: 2
  build:
    jobs:
      - inline-js-test-nix
      - inline-js-test-stack
