version: 2

jobs:
  inline-js-test-nix-nodejs-v8:
    docker:
      - image: terrorjack/pixie:debian
    steps:
      - run:
          name: Install dependencies
          command: |
            apt update
            apt full-upgrade -y
            nix-channel --add https://releases.nixos.org/nixpkgs/nixpkgs-20.03pre193309.c4196cca9ac nixpkgs
            nix-channel --update
            nix-env -u
            nix-env -iA \
              nixpkgs.curl \
              nixpkgs.gitMinimal \
              nixpkgs.openssh \
              nixpkgs.python3
            cd /usr
            curl -L https://raw.githubusercontent.com/tweag/asterius/master/utils/v8-node.py | python3
            export npm_config_prefix=/usr
            curl -L https://www.npmjs.com/install.sh | sh
      - checkout
      - run:
          name: Test inline-js
          command: |
            nix-shell \
              --command "cabal new-run -j2 inline-js:inline-js-test-suite -- -j2" \
              -p cabal-install \
              -p "haskellPackages.ghcWithPackages (pkgs: [pkgs.aeson pkgs.base64-bytestring pkgs.language-javascript pkgs.tasty-hunit pkgs.tasty-quickcheck pkgs.tasty-smallcheck])"

  inline-js-test-nix-nodejs-12:
    docker:
      - image: terrorjack/pixie:latest
    steps:
      - run:
          name: Install dependencies
          command: |
            nix-channel --add https://releases.nixos.org/nixpkgs/nixpkgs-20.03pre193309.c4196cca9ac nixpkgs
            nix-channel --update
            nix-env -u
            nix-env -iA \
              nixpkgs.gitMinimal \
              nixpkgs.openssh
      - checkout
      - run:
          name: Test inline-js
          command: |
            nix-shell \
              --command "cabal new-run -j2 inline-js:inline-js-test-suite -- -j2" \
              --pure \
              -p cabal-install \
              -p nodejs-12_x \
              -p "haskellPackages.ghcWithPackages (pkgs: [pkgs.aeson pkgs.base64-bytestring pkgs.language-javascript pkgs.tasty-hunit pkgs.tasty-quickcheck pkgs.tasty-smallcheck])"

  inline-js-test-stack:
    docker:
      - image: terrorjack/pixie:latest
    steps:
      - run:
          name: Install dependencies
          command: |
            nix-channel --add https://releases.nixos.org/nixpkgs/nixpkgs-20.03pre193309.c4196cca9ac nixpkgs
            nix-channel --update
            nix-env -u
            nix-env -iA \
              nixpkgs.gitMinimal \
              nixpkgs.openssh \
              nixpkgs.stack
      - checkout
      - run:
          name: Test inline-js
          command: |
            stack --nix --no-nix-pure --no-terminal build --haddock --test --no-run-tests
            stack --nix --no-nix-pure --no-terminal test inline-js --test-arguments="-j2"

workflows:
  version: 2
  build:
    jobs:
      - inline-js-test-nix-nodejs-v8
      - inline-js-test-nix-nodejs-12
      - inline-js-test-stack
