version: 2

jobs:
  build:
    docker:
      - image: debian:unstable
    environment:
      - DEBIAN_FRONTEND: noninteractive
      - LANG: C.UTF-8
      - PATH: /root/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    steps:
      - run:
          name: Install dependencies
          command: |
            apt update
            apt install -y \
              apt-transport-https \
              curl \
              gnupg
            curl https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
            echo "deb http://dl.google.com/linux/chrome/deb stable main" > /etc/apt/sources.list.d/google-chrome-unstable.list
            curl https://deb.nodesource.com/gpgkey/nodesource.gpg.key | apt-key add -
            echo "deb https://deb.nodesource.com/node_11.x sid main" > /etc/apt/sources.list.d/nodejs.list
            apt update
            apt full-upgrade -y
            apt install -y \
              gcc \
              git \
              google-chrome-unstable \
              libffi-dev \
              libgmp-dev \
              libncurses-dev \
              libnuma-dev \
              make \
              nodejs \
              openssh-client \
              xz-utils \
              zlib1g-dev
            mkdir -p /root/.local/bin
            curl -L https://get.haskellstack.org/stable/linux-x86_64.tar.gz | tar xz --wildcards --strip-components=1 -C /root/.local/bin '*/stack'
      - checkout
      - restore_cache:
          key: lts-12-17-2-
      - run:
          name: Test inline-js
          command: |
            stack --no-terminal build inline-js --test --no-run-tests
            stack --no-terminal test inline-js:pingpong
            stack --no-terminal test inline-js:eval
            stack --no-terminal test inline-js:puppeteer
      - save_cache:
          paths:
            - /root/.stack/snapshots
            - .stack-work
            - inline-js/.stack-work
          key: lts-12-17-2-{{ .BuildNum }}
