version: 2

jobs:
  inline-js-test-linux:
    docker:
      - image: terrorjack/stackage:lts-14.12
    steps:
      - run:
          name: Install dependencies
          command: |
            mkdir -p ~/.local/bin
            curl -L https://raw.githubusercontent.com/TerrorJack/node-fetcher/master/node-fetcher.py -o ~/.local/bin/node-fetcher
            chmod u+x ~/.local/bin/node-fetcher
      - checkout
      - run:
          name: Test inline-js
          command: |
            mkdir ~/node
            export PATH=~/node/bin:$PATH

            stack --no-terminal -j2 build --haddock --test --no-run-tests

            node-fetcher --channel release --version v12 --path ~/node
            node --version
            npm --version
            stack --no-terminal test inline-js:inline-js-test-suite --test-arguments="-j2"
            rm -rf ~/node/*

            node-fetcher --channel release --version v13 --path ~/node
            node --version
            npm --version
            stack --no-terminal test inline-js:inline-js-test-suite --test-arguments="-j2"
            rm -rf ~/node/*

            node-fetcher --channel v8-canary --path ~/node
            node --version
            npm --version
            stack --no-terminal test inline-js:inline-js-test-suite --test-arguments="-j2"
            rm -rf ~/node/*

  inline-js-test-macos:
    macos:
      xcode: "11.1.0"
    steps:
      - run:
          name: Install dependencies
          command: |
            brew install \
              gnu-tar
            mkdir -p ~/.local/bin
            curl -L https://get.haskellstack.org/stable/osx-x86_64.tar.gz | gtar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
      - checkout
      - run:
          name: Test inline-js
          command: |
            mkdir ~/node
            export PATH=~/.local/bin:~/node/bin:$PATH

            stack --no-terminal -j4 build --haddock --test --no-run-tests

            node-fetcher --channel release --version v12 --path ~/node
            node --version
            npm --version
            stack --no-terminal test inline-js:inline-js-test-suite --test-arguments="-j4"
            rm -rf ~/node/*

            node-fetcher --channel release --version v13 --path ~/node
            node --version
            npm --version
            stack --no-terminal test inline-js:inline-js-test-suite --test-arguments="-j4"
            rm -rf ~/node/*

            node-fetcher --channel v8-canary --path ~/node
            node --version
            npm --version
            stack --no-terminal test inline-js:inline-js-test-suite --test-arguments="-j4"
            rm -rf ~/node/*

workflows:
  version: 2
  build:
    jobs:
      - inline-js-test-linux
      - inline-js-test-macos
