version: 2

jobs:
  build:
    docker:
      - image: terrorjack/pixie:latest
    resource_class: xlarge
    steps:
      - run:
          name: Install dependencies
          command: |
            nix-channel --add https://releases.nixos.org/nixpkgs/nixpkgs-19.09pre174594.0c0954781e2 nixpkgs
            nix-channel --update
            nix-env -u
            nix-env -iA \
              nixpkgs.gitMinimal \
              nixpkgs.gnutar \
              nixpkgs.gzip \
              nixpkgs.openssh \
              nixpkgs.stack
      - checkout
      - run:
          name: Test inline-js
          command: |
            stack --nix --no-terminal build --test --no-run-tests
            stack --nix --no-terminal test inline-js --test-arguments="-j8"
