name: inline-js
version: 0.0.1
category: Web
stability: alpha
maintainer: Shao Cheng <cheng.shao@tweag.io>
copyright: (c) 2018 Tweag I/O
license: BSD3
github: tweag/inline-js

extra-source-files:
  - LICENSE

ghc-options:
  - -Wall
  - -Wcompat
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wredundant-constraints
  - -Wnoncanonical-monad-instances

dependencies:
  - aeson
  - base
  - bytestring
  - inline-js-core
  - language-javascript
  - template-haskell
  - text

library:
  source-dirs: src

tests:
  inline-js-test-suite:
    source-dirs: tests
    main: Main.hs
    ghc-options:
      - -Wall
      - -Wcompat
      - -Wincomplete-record-updates
      - -Wincomplete-uni-patterns
      - -Wredundant-constraints
      - -Wnoncanonical-monad-instances
    dependencies:
      - containers
      - inline-js-core
      - inline-js
      - tasty
      - tasty-hspec
