name: inline-js
version: 0.0.1
category: Web
stability: alpha
maintainer: Shao Cheng <cheng.shao@tweag.io>
copyright: (c) 2018 Tweag I/O
license: BSD3
github: tweag/inline-js

extra-source-files:
  - CHANGELOG.md
  - LICENSE
  - README.md

data-files:
  - jsbits/server.js

ghc-options:
  - -Wall
  - -Wcompat
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wredundant-constraints
  - -Wnoncanonical-monad-instances

dependencies:
  - base
  - binary
  - bytestring
  - containers
  - filepath
  - ghc-prim
  - process
  - stm
  - text

library:
  source-dirs: src
  other-modules: Paths_inline_js

tests:
  pingpong:
    source-dirs: tests
    main: pingpong.hs
    ghc-options: -threaded -with-rtsopts=-N
    dependencies:
      - inline-js
      - QuickCheck

  eval:
    source-dirs: tests
    main: eval.hs
    ghc-options: -threaded -with-rtsopts=-N
    dependencies:
      - inline-js

tests:
  inline-js-test-suite:
    source-dirs: tests
    main: Main.hs
    ghc-options:
    - -Wall
    - -Wcompat
    - -Wincomplete-record-updates
    - -Wincomplete-uni-patterns
    - -Wredundant-constraints
    - -Wnoncanonical-monad-instances
    dependencies:
      - inline-js
      - QuickCheck
      - tasty
      - tasty-hspec
      - tasty-quickcheck