name: inline-javascript-examples
version: 0.0.1

custom-setup:
  dependencies:
    - base
    - Cabal
    - inline-javascript

ghc-options: -Wall

dependencies:
  - aeson
  - base
  - inline-js
  - template-haskell

tests:
  inline-javascript-examples:
    source-dirs: test
    main: inline-javascript-examples.hs
    other-extensions:
      - OverloadedStrings
      - QuasiQuotes
      - TemplateHaskell
