name: inline-js-examples
version: 0.0.1

custom-setup:
  dependencies:
    - base
    - Cabal
    - inline-js

ghc-options: -Wall

dependencies:
  - aeson
  - base
  - inline-js
  - template-haskell
  - unliftio

tests:
  inline-js-examples:
    source-dirs: test
    main: inline-js-examples.hs
    other-extensions:
      - OverloadedStrings
      - QuasiQuotes
      - TemplateHaskell
