name: inline-js-core
version: 0.0.1.0
category: Web
maintainer: Shao Cheng <cheng.shao@tweag.io>
copyright: (c) 2018 Tweag I/O
license: BSD-3-Clause
github: tweag/inline-js
synopsis: Call JavaScript from Haskell.
description: Please see <https://github.com/tweag/inline-js> for details.

extra-source-files:
  - jsbits/**
  - CHANGELOG.md
  - LICENSE
  - README.md

ghc-options: -Wall

dependencies:
  - Cabal
  - base >= 4.13 && < 5
  - binary
  - bytestring
  - containers
  - directory
  - filepath
  - ghc-prim
  - process
  - template-haskell
  - text

library:
  source-dirs: src
  generated-other-modules:
    - Paths_inline_js_core
  exposed-modules:
    - Language.JavaScript.Inline.Core

tests:
  inline-js-core-tests:
    source-dirs: tests
    main: inline-js-core-tests.hs
    ghc-options: -threaded -rtsopts
    dependencies:
      - inline-js-core
      - tasty
      - tasty-hunit
