name: inline-javascript
version: 0.0.1
category: Language
synopsis: Execute Node.js scripts in Haskell.
stability: alpha
maintainer: Shao Cheng <astrohavoc@gmail.com>
copyright: (c) 2018 EURL Tweag
license: BSD3
github: TerrorJack/inline-javascript

extra-source-files:
  - LICENSE
  - README.md
  - CHANGELOG.md

data-files:
  - jsbits/package.json
  - jsbits/server.js

custom-setup:
  dependencies:
    - base
    - binary
    - Cabal

ghc-options: -Wall

dependencies:
  - aeson
  - base
  - binary
  - bytestring
  - Cabal
  - containers
  - directory
  - extra
  - filepath
  - http-client
  - http-types
  - process
  - stache
  - template-haskell
  - text
  - unordered-containers

library:
  source-dirs: src
  other-extensions:
    - DeriveAnyClass
    - DuplicateRecordFields
    - LambdaCase
    - OverloadedStrings
    - RankNTypes
    - RecordWildCards
    - ScopedTypeVariables
    - StrictData
    - TemplateHaskell
