name: pipeline

on:
  - push
  - pull_request

jobs:

  nix:
    name: nix-${{ matrix.os }}-${{ matrix.ghc }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
        ghc:
          - ghc8104
          - ghc884
          - ghc865
    env:
      ghc: ${{ matrix.ghc }}
    steps:

      - name: checkout
        uses: actions/checkout@v2

      - name: setup-nix
        uses: cachix/install-nix-action@v13
        with:
          extra_nix_config: |
            substituters = https://cache.nixos.org https://hydra.iohk.io
            trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ=

      - name: setup-cachix
        uses: cachix/cachix-action@v9
        with:
          name: asterius
          signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'

      - name: test
        run: |
          for node in nodejs-15_x nodejs-14_x nodejs-12_x nodejs-10_x; do
            nix run --keep-going -f . -i --argstr ghc $ghc --argstr node $node inline-js-tests.components.exes.inline-js-tests -c inline-js-tests -j2
          done

      - name: test-nix-shell
        run: |
          for node in nodejs-15_x nodejs-14_x nodejs-12_x nodejs-10_x; do
            nix-shell --keep-going --pure --argstr ghc $ghc --argstr node $node --run "cabal v2-run inline-js-tests:inline-js-tests -- -j2"
          done

  stack:
    name: stack-${{ matrix.os }}-${{ matrix.resolver }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - windows-latest
        resolver:
          - lts-17
          - lts-16
          - lts-14
    steps:

      - name: checkout
        uses: actions/checkout@v2

      - name: setup-haskell
        id: setup-haskell
        uses: haskell/actions/setup@v1
        with:
          enable-stack: true
          stack-no-global: true

      - name: cache
        uses: actions/cache@v2
        with:
          key: stack-${{ matrix.os }}-${{ matrix.resolver }}-${{ github.run_id }}
          restore-keys: stack-${{ matrix.os }}-${{ matrix.resolver }}-
          path: |
            ${{ steps.setup-haskell.outputs.stack-root }}
            **/.stack-work

      - name: build
        run: |
          stack --resolver ${{ matrix.resolver }} -j2 build --test --no-run-tests

      - name: setup-node-15
        uses: actions/setup-node@v2
        with:
          node-version: 15
          check-latest: true

      - name: test-node-15
        run: |
          node --version
          stack --resolver ${{ matrix.resolver }} run inline-js-tests -- -j2

      - name: setup-node-14
        uses: actions/setup-node@v2
        with:
          node-version: 14
          check-latest: true

      - name: test-node-14
        run: |
          node --version
          stack --resolver ${{ matrix.resolver }} run inline-js-tests -- -j2

      - name: setup-node-13
        uses: actions/setup-node@v2
        with:
          node-version: 13
          check-latest: true

      - name: test-node-13
        run: |
          node --version
          stack --resolver ${{ matrix.resolver }} run inline-js-tests -- -j2

      - name: setup-node-12
        uses: actions/setup-node@v2
        with:
          node-version: 12
          check-latest: true

      - name: test-node-12
        run: |
          node --version
          stack --resolver ${{ matrix.resolver }} run inline-js-tests -- -j2

      - name: setup-node-10
        uses: actions/setup-node@v2
        with:
          node-version: 10
          check-latest: true

      - name: test-node-10
        run: |
          node --version
          stack --resolver ${{ matrix.resolver }} run inline-js-tests -- -j2

  sdist:
    name: sdist
    runs-on: ubuntu-latest
    steps:

      - name: checkout
        uses: actions/checkout@v2

      - name: setup-nix
        uses: cachix/install-nix-action@v13
        with:
          extra_nix_config: |
            substituters = https://cache.nixos.org https://hydra.iohk.io
            trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ=

      - name: setup-cachix
        uses: cachix/cachix-action@v9
        with:
          name: asterius
          signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'

      - name: sdist
        run: |

          for pkg in inline-js inline-js-core inline-js-examples inline-js-tests; do
            nix-shell --keep-going --pure --run "cd $pkg && cabal check"
          done

          nix-shell --keep-going --pure --run "cabal v2-sdist all"

      - name: upload-artifact
        uses: actions/upload-artifact@v2
        with:
          name: sdist
          path: dist-newstyle/sdist/*.tar.gz

  haddock:
    name: haddock
    runs-on: ubuntu-latest
    steps:

      - name: checkout
        uses: actions/checkout@v2

      - name: setup-nix
        uses: cachix/install-nix-action@v13
        with:
          extra_nix_config: |
            substituters = https://cache.nixos.org https://hydra.iohk.io
            trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ=

      - name: setup-cachix
        uses: cachix/cachix-action@v9
        with:
          name: asterius
          signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'

      - name: haddock
        run: |
          nix-shell --keep-going --pure --run "cabal v2-haddock --haddock-for-hackage --haddock-hyperlink-source --haddock-quickjump -j2 all"

      - name: upload-artifact
        uses: actions/upload-artifact@v2
        with:
          name: haddock
          path: dist-newstyle/*-docs.tar.gz

  docs:
    name: docs
    runs-on: ubuntu-latest
    env:
      NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
      NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
    steps:

      - name: checkout
        uses: actions/checkout@v2

      - name: setup-haskell
        id: setup-haskell
        uses: haskell/actions/setup@v1
        with:
          enable-stack: true
          stack-no-global: true

      - name: cache
        uses: actions/cache@v2
        with:
          key: docs-${{ github.run_id }}
          restore-keys: docs-
          path: |
            ${{ steps.setup-haskell.outputs.stack-root }}
            **/.stack-work

      - name: setup-node-15
        uses: actions/setup-node@v2
        with:
          node-version: 15
          check-latest: true

      - name: setup-deps
        run: |
          npm config set prefix ~/.local

          npm install -g \
            netlify-cli

      - name: build
        run: |
          export PATH=~/.local/bin:$PATH

          stack -j2 build --haddock

          if [ ! -z "$NETLIFY_AUTH_TOKEN" ]
          then
            if [ $(git rev-parse --abbrev-ref HEAD) = "master" ]
            then
              netlify deploy --dir $(stack path --local-doc-root) --message "$GITHUB_REF-$GITHUB_SHA" --prod
            else
              netlify deploy --dir $(stack path --local-doc-root) --message "$GITHUB_REF-$GITHUB_SHA"
            fi
          fi
