name: pipeline

on:
  - push
  - pull_request

jobs:

  cabal:
    name: cabal-${{ matrix.os }}-ghc-${{ matrix.ghc }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-20.04
          - macos-10.15
          - windows-2019
        ghc:
          - 8.10.1
          - 8.8.4
    steps:

      - name: setup-haskell
        uses: actions/setup-haskell@v1
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: 3.2.0.0

      - name: checkout
        uses: actions/checkout@v2

      - name: build
        run: |
          cabal v2-build --enable-tests -j2 all

      - name: setup-node-14
        uses: actions/setup-node@v2.0.0
        with:
          node-version: 14.5.0

      - name: test-node-14
        run: |
          node --version
          cabal v2-run inline-js-tests:inline-js-tests -- -j2

      - name: setup-node-13
        uses: actions/setup-node@v2.0.0
        with:
          node-version: 13.14.0

      - name: test-node-13
        run: |
          node --version
          cabal v2-run inline-js-tests:inline-js-tests -- -j2

      - name: setup-node-12
        uses: actions/setup-node@v2.0.0
        with:
          node-version: 12.18.2

      - name: test-node-12
        run: |
          node --version
          cabal v2-run inline-js-tests:inline-js-tests -- -j2

      - name: setup-node-10
        uses: actions/setup-node@v2.0.0
        with:
          node-version: 10.21.0

      - name: test-node-10
        run: |
          node --version
          cabal v2-run inline-js-tests:inline-js-tests -- -j2

  stack:
    name: stack-${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-20.04
          - macos-10.15
          - windows-2019
    steps:

      - name: setup-haskell
        uses: actions/setup-haskell@v1
        with:
          stack-version: 2.3.1
          enable-stack: true
          stack-no-global: true

      - name: checkout
        uses: actions/checkout@v2

      - name: build
        run: |
          stack -j2 build --test --no-run-tests

      - name: setup-node-14
        uses: actions/setup-node@v2.0.0
        with:
          node-version: 14.5.0

      - name: test-node-14
        run: |
          node --version
          stack test inline-js-tests --test-arguments="-j2"

      - name: setup-node-13
        uses: actions/setup-node@v2.0.0
        with:
          node-version: 13.14.0

      - name: test-node-13
        run: |
          node --version
          stack test inline-js-tests --test-arguments="-j2"

      - name: setup-node-12
        uses: actions/setup-node@v2.0.0
        with:
          node-version: 12.18.2

      - name: test-node-12
        run: |
          node --version
          stack test inline-js-tests --test-arguments="-j2"

      - name: setup-node-10
        uses: actions/setup-node@v2.0.0
        with:
          node-version: 10.21.0

      - name: test-node-10
        run: |
          node --version
          stack test inline-js-tests --test-arguments="-j2"

  stack-alpine:
    name: stack-alpine
    runs-on: ubuntu-20.04
    container:
      image: alpine:edge
    steps:

      - name: checkout
        uses: actions/checkout@v2

      - name: test
        run: |
          export HOME=/root
          mkdir -p $HOME/.local/bin
          mkdir $HOME/.node
          export PATH=$HOME/.local/bin:$HOME/.node/bin:$PATH

          apk add \
            alpine-sdk \
            autoconf \
            bash \
            coreutils \
            gmp-dev \
            grep \
            libffi-dev \
            ncurses-dev \
            xz
          ln -s /usr/lib/libncursesw.so.6 /usr/lib/libtinfow.so.6

          mkdir $HOME/.stack
          echo "allow-different-user: true" > $HOME/.stack/config.yaml
          echo "ghc-build: musl" >> $HOME/.stack/config.yaml
          curl -L https://github.com/commercialhaskell/stack/releases/download/v2.3.1/stack-2.3.1-linux-x86_64-bin -o $HOME/.local/bin/stack
          chmod +x $HOME/.local/bin/stack

          stack -j2 build --test --no-run-tests

          rm -rf $HOME/.node/*
          curl https://unofficial-builds.nodejs.org/download/release/v14.5.0/node-v14.5.0-linux-x64-musl.tar.xz | tar xJ -C $HOME/.node --strip 1
          node --version
          stack test inline-js-tests --test-arguments="-j2"

          rm -rf $HOME/.node/*
          curl https://unofficial-builds.nodejs.org/download/release/v13.14.0/node-v13.14.0-linux-x64-musl.tar.xz | tar xJ -C $HOME/.node --strip 1
          node --version
          stack test inline-js-tests --test-arguments="-j2"

          rm -rf $HOME/.node/*
          curl https://unofficial-builds.nodejs.org/download/release/v12.18.2/node-v12.18.2-linux-x64-musl.tar.xz | tar xJ -C $HOME/.node --strip 1
          node --version
          stack test inline-js-tests --test-arguments="-j2"

          rm -rf $HOME/.node/*
          curl https://unofficial-builds.nodejs.org/download/release/v10.21.0/node-v10.21.0-linux-x64-musl.tar.xz | tar xJ -C $HOME/.node --strip 1
          node --version
          stack test inline-js-tests --test-arguments="-j2"

  sdist:
    name: sdist
    runs-on: ubuntu-20.04
    steps:

      - name: setup-haskell
        uses: actions/setup-haskell@v1
        with:
          ghc-version: 8.10.1
          cabal-version: 3.2.0.0

      - name: checkout
        uses: actions/checkout@v2

      - name: sdist
        run: |
          pushd inline-js
          cabal check
          popd

          pushd inline-js-core
          cabal check
          popd

          pushd inline-js-tests
          cabal check
          popd

          cabal v2-sdist \
            all

      - name: upload-artifact
        uses: actions/upload-artifact@v2
        with:
          name: sdist
          path: dist-newstyle/sdist/*.tar.gz

  haddock:
    name: haddock
    runs-on: ubuntu-20.04
    steps:

      - name: setup-haskell
        uses: actions/setup-haskell@v1
        with:
          ghc-version: 8.10.1
          cabal-version: 3.2.0.0

      - name: checkout
        uses: actions/checkout@v2

      - name: haddock
        run: |
          cabal v2-haddock \
            --haddock-for-hackage \
            --haddock-hyperlink-source \
            --haddock-quickjump \
            -j2 \
            all

      - name: upload-artifact
        uses: actions/upload-artifact@v2
        with:
          name: haddock
          path: dist-newstyle/*-docs.tar.gz

  docs:
    name: docs
    runs-on: ubuntu-20.04
    env:
      NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
      NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
    steps:

      - name: setup-haskell
        uses: actions/setup-haskell@v1
        with:
          stack-version: 2.3.1
          enable-stack: true
          stack-no-global: true

      - name: setup-node-14
        uses: actions/setup-node@v2.0.0
        with:
          node-version: 14.5.0

      - name: setup-deps
        run: |
          npm install -g \
            netlify-cli

      - name: checkout
        uses: actions/checkout@v2

      - name: build
        run: |
          stack -j2 build --haddock

          if [ ! -z "$NETLIFY_AUTH_TOKEN" ]
          then
            if [ $(git rev-parse --abbrev-ref HEAD) = "master" ]
            then
              netlify deploy --dir $(stack path --local-doc-root) --message "$GITHUB_REF-$GITHUB_SHA" --prod
            else
              netlify deploy --dir $(stack path --local-doc-root) --message "$GITHUB_REF-$GITHUB_SHA"
            fi
          fi
